### PR TITLE
Added support for 2020

### LINKED ISSUE #2: Add support for 2020 organisations
Could you please update the repository and add support for the organizations for 2020

### PR DESCRIPTION
**Pull request by priyanshuone6**
Fixes #2 
Updated scrape.py
Updated finalData.json by adding 2020 organizations

### CODE REVIEW

**Comment by Sparsh1212** [comment]
Good Job! @priyanshuone6

**Comment by priyanshuone6** [comment]
Wait

**Comment by priyanshuone6** [comment]
I think I did a mistake, look at the line 21, 23, 24, 26 in finalData, they all have 2015

**Comment by Sparsh1212** [comment]
Yeah!, I also noticed it just now. As of now, I am reverting the changes to the previous commit. Till then you could work on fixing this.

**Pull request merged**
