### PR TITLE
Add feature to search for multiple tags in tech and topic filter

### LINKED ISSUE #49: Introduce Searching with multiple tags Feature
Add a new feature that allows the user to search for projects using multiple 'tags'. This would help the user get more specific information and get it faster.

For Ex: Search for projects that use both Python AND Javascript

This could be achieved by modifying the search bar to hold multiple 'tags' simultaneously (any other working method is also fine)

Note: We can also allow the user to choose multiple search 'tags' of different types (Tech Stack, Org Name, etc.) simultaneously.

### PR DESCRIPTION
**Pull request by letsintegreat**
Add feature to search for multiple tags in tech and topic filter, using comma as a separator

## Issue
Fixes #49

## Description

Now users can search for multiple tags in tech-stack and topic by using comma separator. I have also removed the space character from sanitized search.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by Sparsh1212** [comment]
@letsintegreat Can you please upload a demo video for this PR?

**Comment by Sparsh1212** [comment]
Also, as you mentioned about removing the space character from the search query, so won't that affect the search results for organizations that have a space character in their name.
`Wikimedia Foundation` will convert to: `WikimediaFoundation`, this might lead to the wrong search results.
WDYT?

**Comment by letsintegreat** [comment]
> @letsintegreat Can you please upload a demo video for this PR?

https://imgur.com/a/CbJbga7

> Also, as you mentioned about removing the space character from the search query, so won't that affect the search results for organizations that have a space character in their name.
Wikimedia Foundation will convert to: WikimediaFoundation, this might lead to the wrong search results.
WDYT?

That makes perfect sense, I think I should just remove trailing and leading spaces instead of all the spaces, so as to make comma separation work fine.

**Comment by letsintegreat** [comment]
@Sparsh1212 Done.

**Review by Sparsh1212 — CHANGES_REQUESTED** [review]
I think it will be better to give results based on union rather than intersection of all tags. This is because most of the time people want to search with multiple tags in hand and they'd want to see all organizations matching any one of them. So, if any item of the `search` array matches the tech/topic of org, we can show that in the search result.
Let me know your views on this.

**Comment by letsintegreat** [comment]
@Sparsh1212 Yes, union sounds more promising. Changed.

**Review by Sparsh1212 — APPROVED** [review]
LGTM!

**Pull request merged**
