### PR TITLE
added templates for issue and PR 

### PR DESCRIPTION
**Pull request by Pranav108**
This PR will fix issue #59, here I have added a issue and Pull request template.

### CODE REVIEW

**Review by Sparsh1212 — CHANGES_REQUESTED** [review]
Why are the same files are added under the `temp` directory?
Any reason for that

**Comment by Pranav108** [comment]
Tbh, I don't know the reason for that.
Initially I haven't added any extra folder and pushed changes in my local branch and doesn't find any positive impact.
Then I found a repo where this the file were added in temp folder and it that repo was working fine for me ,so I did the same here in hope to working this way : )

**Comment by Sparsh1212** [comment]
> Tbh, I don't know the reason for that. Initially I haven't added any extra folder and pushed changes in my local branch and doesn't find any positive impact. Then I found a repo where this the file were added in temp folder and it that repo was working fine for me ,so I did the same here in hope to working this way : )

Okay, no problem. Can you try reverting the `temp` directory changes and try to push only the two required files. Let me know if you face any problems.

**Review by Pranav108 — COMMENTED** [review]
Removed redundant files

**Review by Sparsh1212 — APPROVED** [review]
LGTM!

**Comment by Pranav108** [comment]
@Sparsh1212  Did you added point for PR too, I think you only added for issue points?

**Comment by Sparsh1212** [comment]
> @Sparsh1212 Did you added point for PR too, I think you only added for issue points?

You have been allotted two points. 1 for the issue (Already allotted at the time of opening the issue) and 1 for the fix. Since this was a relatively very easy issue.

**Pull request merged**
