### PR TITLE
added suggestion based on search query

### PR DESCRIPTION
**Pull request by SuyashSonawane**
### Add suggestions based on filter and user query
---
This PR adds the feature request mentioned in #24, #19 and #21 as all can we implemented in the same way.

image
image
### responsive 
image

Demo available here https://suyashsonawane.me/gsocanalyzer/

### CODE REVIEW

**Comment by Sparsh1212** [comment]
This looks super awesome to me!
Can you please also take into account one more issue, which isn't there currently, i.e: search suggestions by "Topic",
that way, this will be a complete PR for all search suggestions features.

Btw, commendable job!

**Comment by SuyashSonawane** [comment]
I added the suggestions for all the filters 🙌

**Comment by Sparsh1212** [comment]
> I added the suggestions for all filters 🙌

This is awesome!
I Will test this out and will get back to you!
Thanks.

**Review by Sparsh1212 — CHANGES_REQUESTED** [review]
Some thoughts:

- The outline for the search suggestions dropdown slightly looks odd on top of the search box. Can we fix that a bit? (We can reduce the width of the search box if necessary, as it's a bit wider than required, so feel free to do whatever seems the best to you)
- When the user focuses on the input, can we show the show all the search suggestions by default, currently, if we type something and clear that out, then only we can see the list of all suggestions, so if it is possible to display the full list when the search input comes into focus,  that would actually be great!
- The last thing is about something that I am not sure, (if it's a problem with my browser). The browser's auto fill search suggestions are overlapping with the suggestions that we are providing. Could that be avoided? (I am not sure, how we can disable that, but please see if something could be done about it)

**Comment by SuyashSonawane** [comment]
I'll work on it

**Comment by SuyashSonawane** [comment]
Implemented new changes!

**Comment by Sparsh1212** [comment]
> Implemented new changes!

Great!
Can you please also deploy those changes? That will make testing a lot easier for me, and will merge it :)

**Comment by Sparsh1212** [comment]
> > Implemented new changes!
> 

@SuyashSonawane 
> Great! Can you please also deploy those changes? That will make testing a lot easier for me, and will merge it :)

**Comment by Sparsh1212** [comment]
> > > Implemented new changes!
> 
> @SuyashSonawane Great! Can you please also deploy those changes? That will make testing a lot easier for me, and will merge it :)

nvm! i tested that locally, everything looks correct to me.

**Comment by Sparsh1212** [comment]
> > > > Implemented new changes!
> > 
> > 
> > @SuyashSonawane Great! Can you please also deploy those changes? That will make testing a lot easier for me, and will merge it :)
> 
> nvm! I tested that locally, everything looks correct to me.

**Review by Sparsh1212 — APPROVED** [review]
Must say, awesome work!
This is going to simplify things, a lot for the users.
Thank you so much for the feature implementation!

**Comment by SuyashSonawane** [comment]
Thanks, @Sparsh1212 for reviewing and merging my contributions 💯
The project is very awesome too.

**Pull request merged**
